---
title: "Blue Sky and Oceans"
url: "https://bsojapan.github.io"
permalink: /blog0/:year/:month/:day/:title.html

# plugins: の代わりに、古い互換性を持たせる書き方にしてみる
gems:
  - jekyll-sitemap
contents_subtitle_i: " -- Index"
contents_subtitle_c: " -- Vehicles Overview"
---

